services:
  - type: web
    name: qrcodeapp
    env: swift
    plan: free
    buildCommand: swift build -c release
    startCommand: .build/release/QRCodeApp serve --env production --hostname 0.0.0.0 --port $PORT
